#Docker-compose file for the honeypot system

version: '3'
services:

  maindb:
    image: mongo:latest
    restart: always
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=example

  monitor_server:
    build: 'monitor_server'
    depends_on:
     - "maindb"
    ports:
     - "8085:8085"
      
  traps_generator:
    build: 'traps_generator'
    depends_on:
     - "maindb"
    volumes:
     - .\TrapsZip:/HoneyPot/TrapsZip
    ports:
     - "8090:8090"
        
  user_interface:
    build: 'user_interface'
    depends_on:
     - "maindb"
     - "traps_generator"
     - "monitor_server"
    volumes:
     - .\TrapsZip:/HoneyPot/TrapsZip
    ports:
     - "8080:8080"

  
